"""init: users roles audit_logs codebook prompt_templates

Revision ID: 02808ce30c7b
Revises: 
Create Date: 2026-02-11 12:55:17.311979
"""
from typing import Sequence, Union

import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02808ce30c7b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False, comment='链路追踪ID'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='用户ID'),
    sa.Column('username', sa.String(length=64), nullable=True, comment='用户名（冗余，方便查询）'),
    sa.Column('action', sa.String(length=32), nullable=False, comment='操作类型: query/analyze/write/approve'),
    sa.Column('risk_level', sa.String(length=16), server_default='read', nullable=False, comment='风险等级: read/suggest/write/critical'),
    sa.Column('route', sa.String(length=16), nullable=True, comment='路由: fast_track/deep_engine'),
    sa.Column('input_text', sa.Text(), nullable=True, comment='用户原始输入（完整保存）'),
    sa.Column('status', sa.String(length=16), server_default='success', nullable=False, comment='状态: success/blocked/error'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='扩展字段'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='请求耗时(毫秒)'),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    schema='sunny_agent'
    )
    op.create_index(op.f('ix_sunny_agent_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False, schema='sunny_agent')
    op.create_table('codebook',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=128), nullable=False, comment='归一化别名，如 a100'),
    sa.Column('alias_display', sa.String(length=128), nullable=False, comment='原始展示名，如 A-100'),
    sa.Column('standard_name', sa.String(length=128), nullable=False, comment='标准名称'),
    sa.Column('entity_type', sa.String(length=32), nullable=False, comment='实体类型: product/line/metric/department'),
    sa.Column('entity_meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='扩展属性'),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False, comment='状态: active/candidate/deprecated'),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.String(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias', 'entity_type', name='uq_codebook_alias_type'),
    schema='sunny_agent'
    )
    op.create_table('prompt_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='模板名称'),
    sa.Column('intent_pattern', sa.String(length=128), nullable=False, comment='匹配的意图模式'),
    sa.Column('category', sa.String(length=32), nullable=False, comment='分类: query/write/summarize/translate/general'),
    sa.Column('template', sa.Text(), nullable=False, comment='Jinja2 模板内容'),
    sa.Column('version', sa.String(length=16), server_default='1.0.0', nullable=False, comment='版本号'),
    sa.Column('tenant_id', sa.String(length=64), server_default='default', nullable=False, comment='租户ID'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='是否启用'),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default='{"usage_count": 0, "avg_accuracy": 0, "avg_rt_ms": 0}', nullable=False, comment='使用指标'),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.String(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', 'tenant_id', name='uq_template_name_ver_tenant'),
    schema='sunny_agent'
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False, comment='角色名'),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='权限列表'),
    sa.Column('description', sa.Text(), nullable=True, comment='角色描述'),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='sunny_agent'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱'),
    sa.Column('hashed_pwd', sa.String(length=256), nullable=False, comment='密码哈希'),
    sa.Column('role_id', sa.UUID(), nullable=False, comment='角色ID'),
    sa.Column('department', sa.String(length=64), nullable=True, comment='部门'),
    sa.Column('data_scope', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='数据权限范围'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='是否激活'),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.String(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['role_id'], ['sunny_agent.roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='sunny_agent'
    )
    # ### end Alembic commands ###

    # ── 预置角色 ──
    roles_table = sa.table(
        'roles',
        sa.column('id', sa.UUID),
        sa.column('name', sa.String),
        sa.column('permissions', postgresql.JSONB),
        sa.column('description', sa.Text),
        schema='sunny_agent',
    )
    admin_role_id = uuid.uuid4()
    manager_role_id = uuid.uuid4()
    operator_role_id = uuid.uuid4()
    viewer_role_id = uuid.uuid4()

    op.bulk_insert(roles_table, [
        {'id': admin_role_id, 'name': 'admin', 'permissions': ['*'], 'description': '系统管理员，全权限'},
        {'id': manager_role_id, 'name': 'manager', 'permissions': ['read:*', 'write:report', 'approve:critical'], 'description': '管理者，可审批关键操作'},
        {'id': operator_role_id, 'name': 'operator', 'permissions': ['read:quality', 'read:production', 'write:report'], 'description': '操作员，可查看质量/生产数据、提交报告'},
        {'id': viewer_role_id, 'name': 'viewer', 'permissions': ['read:quality'], 'description': '只读用户'},
    ])

    # ── 预置 admin 用户（密码: admin123）──
    # 预计算的 bcrypt hash，避免 passlib 版本兼容问题
    hashed = "$2b$12$rFg252raLo8yvjh7KXOub.TLaOhjJQjYKcKaTo00cAp1HlVqnVeC."

    users_table = sa.table(
        'users',
        sa.column('id', sa.UUID),
        sa.column('username', sa.String),
        sa.column('hashed_pwd', sa.String),
        sa.column('role_id', sa.UUID),
        sa.column('department', sa.String),
        sa.column('data_scope', postgresql.JSONB),
        schema='sunny_agent',
    )
    op.bulk_insert(users_table, [
        {'id': uuid.uuid4(), 'username': 'admin', 'hashed_pwd': hashed, 'role_id': admin_role_id, 'department': '技术部', 'data_scope': {}},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='sunny_agent')
    op.drop_table('roles', schema='sunny_agent')
    op.drop_table('prompt_templates', schema='sunny_agent')
    op.drop_table('codebook', schema='sunny_agent')
    op.drop_index(op.f('ix_sunny_agent_audit_logs_created_at'), table_name='audit_logs', schema='sunny_agent')
    op.drop_table('audit_logs', schema='sunny_agent')
    # ### end Alembic commands ###
