"""update_prompt_templates_v4_tier_match_text

Revision ID: 06621b9b3bd3
Revises: 684e135865f9
Create Date: 2026-02-13 10:57:18.266087
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06621b9b3bd3'
down_revision: Union[str, None] = '684e135865f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_templates', sa.Column('tier', sa.String(length=10), server_default='L1', nullable=False, comment='执行层级: L1 / L3'), schema='sunny_agent')
    op.add_column('prompt_templates', sa.Column('intent_tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='关联意图标签，如 ["writing", "summarize"]'), schema='sunny_agent')
    op.add_column('prompt_templates', sa.Column('match_text', sa.Text(), server_default='', nullable=False, comment='用于 embedding 匹配的文本（意图描述 + 示例查询）'), schema='sunny_agent')
    op.add_column('prompt_templates', sa.Column('description', sa.String(length=256), server_default='', nullable=False, comment='模板描述（人类可读）'), schema='sunny_agent')
    op.add_column('prompt_templates', sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False, comment='是否为默认 Prompt'), schema='sunny_agent')
    op.add_column('prompt_templates', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False, comment='排序权重（越大优先级越高）'), schema='sunny_agent')
    op.alter_column('prompt_templates', 'template',
               existing_type=sa.TEXT(),
               comment='Prompt 正文',
               existing_comment='Jinja2 模板内容',
               existing_nullable=False,
               schema='sunny_agent')
    op.drop_column('prompt_templates', 'intent_pattern', schema='sunny_agent')
    op.drop_column('prompt_templates', 'category', schema='sunny_agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_templates', sa.Column('category', sa.VARCHAR(length=32), autoincrement=False, nullable=False, comment='分类: query/write/summarize/translate/general'), schema='sunny_agent')
    op.add_column('prompt_templates', sa.Column('intent_pattern', sa.VARCHAR(length=128), autoincrement=False, nullable=False, comment='匹配的意图模式'), schema='sunny_agent')
    op.alter_column('prompt_templates', 'template',
               existing_type=sa.TEXT(),
               comment='Jinja2 模板内容',
               existing_comment='Prompt 正文',
               existing_nullable=False,
               schema='sunny_agent')
    op.drop_column('prompt_templates', 'sort_order', schema='sunny_agent')
    op.drop_column('prompt_templates', 'is_default', schema='sunny_agent')
    op.drop_column('prompt_templates', 'description', schema='sunny_agent')
    op.drop_column('prompt_templates', 'match_text', schema='sunny_agent')
    op.drop_column('prompt_templates', 'intent_tags', schema='sunny_agent')
    op.drop_column('prompt_templates', 'tier', schema='sunny_agent')
    # ### end Alembic commands ###
