"""add chat_sessions and chat_messages tables

Revision ID: 5582a6f57d74
Revises: 06621b9b3bd3
Create Date: 2026-02-14 10:13:07.861538
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5582a6f57d74'
down_revision: Union[str, None] = '06621b9b3bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False, comment='会话唯一ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='会话标题（首条消息截取前50字）'),
    sa.Column('turn_count', sa.Integer(), nullable=False, comment='对话轮次'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: active / archived'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后活跃时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sunny_agent.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sunny_agent'
    )
    op.create_index(op.f('ix_sunny_agent_chat_sessions_session_id'), 'chat_sessions', ['session_id'], unique=True, schema='sunny_agent')
    op.create_index(op.f('ix_sunny_agent_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False, schema='sunny_agent')
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False, comment='所属会话'),
    sa.Column('message_id', sa.String(length=64), nullable=False, comment='消息唯一ID（防重）'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色: user / assistant'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('intent_primary', sa.String(length=50), nullable=True, comment='主意图'),
    sa.Column('route', sa.String(length=30), nullable=True, comment='路由: standard_l1 / deep_l3'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='使用的 LLM 模型'),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='工具调用记录'),
    sa.Column('reasoning_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='L3 推理轨迹'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['session_id'], ['sunny_agent.chat_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id'),
    schema='sunny_agent'
    )
    op.create_index(op.f('ix_sunny_agent_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False, schema='sunny_agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sunny_agent_chat_messages_session_id'), table_name='chat_messages', schema='sunny_agent')
    op.drop_table('chat_messages', schema='sunny_agent')
    op.drop_index(op.f('ix_sunny_agent_chat_sessions_user_id'), table_name='chat_sessions', schema='sunny_agent')
    op.drop_index(op.f('ix_sunny_agent_chat_sessions_session_id'), table_name='chat_sessions', schema='sunny_agent')
    op.drop_table('chat_sessions', schema='sunny_agent')
    # ### end Alembic commands ###
