"""fix: timestamp columns String to TIMESTAMPTZ, permissions JSONB type

Revision ID: ac2143083ccf
Revises: 02808ce30c7b
Create Date: 2026-02-11 13:12:57.349408
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac2143083ccf'
down_revision: Union[str, None] = '02808ce30c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='sunny_agent',
               postgresql_using='created_at::timestamp with time zone')
    op.alter_column('codebook', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='sunny_agent',
               postgresql_using='created_at::timestamp with time zone')
    op.alter_column('codebook', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='sunny_agent',
               postgresql_using='updated_at::timestamp with time zone')
    op.alter_column('prompt_templates', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='sunny_agent',
               postgresql_using='created_at::timestamp with time zone')
    op.alter_column('prompt_templates', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='sunny_agent',
               postgresql_using='updated_at::timestamp with time zone')
    op.alter_column('roles', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='sunny_agent',
               postgresql_using='created_at::timestamp with time zone')
    op.alter_column('users', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='sunny_agent',
               postgresql_using='created_at::timestamp with time zone')
    op.alter_column('users', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='sunny_agent',
               postgresql_using='updated_at::timestamp with time zone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='sunny_agent',
               postgresql_using='created_at::timestamp with time zone')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='sunny_agent',
               postgresql_using='created_at::timestamp with time zone')
    op.alter_column('roles', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='sunny_agent',
               postgresql_using='created_at::timestamp with time zone')
    op.alter_column('prompt_templates', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='sunny_agent',
               postgresql_using='created_at::timestamp with time zone')
    op.alter_column('prompt_templates', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='sunny_agent',
               postgresql_using='created_at::timestamp with time zone')
    op.alter_column('codebook', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='sunny_agent',
               postgresql_using='created_at::timestamp with time zone')
    op.alter_column('codebook', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='sunny_agent',
               postgresql_using='created_at::timestamp with time zone')
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='sunny_agent',
               postgresql_using='created_at::timestamp with time zone')
    # ### end Alembic commands ###
