"""add_usernumb_to_users

Revision ID: edbe70b998c2
Revises: ac2143083ccf
Create Date: 2026-02-11 13:32:36.033238
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edbe70b998c2'
down_revision: Union[str, None] = 'ac2143083ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('usernumb', sa.String(length=32), nullable=True, comment='人员工号'), schema='sunny_agent')
    op.create_unique_constraint('uq_users_usernumb', 'users', ['usernumb'], schema='sunny_agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_usernumb', 'users', schema='sunny_agent', type_='unique')
    op.drop_column('users', 'usernumb', schema='sunny_agent')
    # ### end Alembic commands ###
